# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 50, 719, 499))
        self.table.setMinimumSize(QtCore.QSize(658, 472))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(730, 50, 175, 35))
        self.add.setMinimumSize(QtCore.QSize(100, 35))
        self.add.setMaximumSize(QtCore.QSize(175, 16777215))
        self.add.setStyleSheet("#add {\n"
                               "background-color: rgb(85, 255, 0);\n"
                               "font: 75 10pt \"MS Shell Dlg 2\";\n"
                               "border-radius: 10px;\n"
                               "border: 5px solid grey;\n"
                               "color: blue;\n"
                               "}\n"
                               "\n"
                               "#add:hover {\n"
                               "border: 5px solid #5555ff;\n"
                               "}")
        self.add.setObjectName("add")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно"))
        self.add.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>После добавления не забудьте обновить!</p></body></html>"))
        self.add.setText(_translate("MainWindow", "Добавить"))
