# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_k(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("k")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(611, 373)
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(220, 300, 175, 35))
        self.add.setMinimumSize(QtCore.QSize(100, 35))
        self.add.setMaximumSize(QtCore.QSize(175, 16777215))
        self.add.setStyleSheet("#add {\n"
                               "background-color: rgb(85, 255, 0);\n"
                               "font: 75 10pt \"MS Shell Dlg 2\";\n"
                               "border-radius: 10px;\n"
                               "border: 5px solid grey;\n"
                               "color: blue;\n"
                               "}\n"
                               "\n"
                               "#add:hover {\n"
                               "border: 5px solid #5555ff;\n"
                               "}")
        self.add.setObjectName("add")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 521, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(161, 30))
        self.label_3.setMaximumSize(QtCore.QSize(161, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(161, 30))
        self.label_2.setMaximumSize(QtCore.QSize(161, 30))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 30))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(161, 30))
        self.label_4.setMaximumSize(QtCore.QSize(161, 30))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(300, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(161, 30))
        self.label_5.setMaximumSize(QtCore.QSize(161, 30))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(300, 30))
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_5.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(161, 30))
        self.label_6.setMaximumSize(QtCore.QSize(161, 30))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setMinimumSize(QtCore.QSize(300, 30))
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_6.addWidget(self.spinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, k):
        _translate = QtCore.QCoreApplication.translate
        k.setWindowTitle(_translate("k", "Dialog"))
        self.add.setToolTip(
            _translate("k", "<html><head/><body><p>После добавления не забудьте обновить!</p></body></html>"))
        self.add.setText(_translate("k", "Продолжить"))
        self.label_3.setText(
            _translate("k", "<html><head/><body><p><span style=\" font-size:12pt;\">Название</span></p></body></html>"))
        self.label_2.setText(_translate("k",
                                        "<html><head/><body><p><span style=\" font-size:12pt;\">Степень обжарки</span></p></body></html>"))
        self.label_4.setText(_translate("k",
                                        "<html><head/><body><p><span style=\" font-size:12pt;\">Структура</span></p></body></html>"))
        self.label_5.setText(
            _translate("k", "<html><head/><body><p><span style=\" font-size:12pt;\">Цена</span></p></body></html>"))
        self.label_6.setText(
            _translate("k", "<html><head/><body><p><span style=\" font-size:12pt;\">Объем</span></p></body></html>"))
